### ISSUE TITLE
请问此书已经出版了吗 在哪可以买到或读到呢

### ISSUE THREAD

**Issue by A-Gan** [luopeiyu/million_game_server#1]
尝试搜索了一下没有找到相关内容

**Comment by luopeiyu** [comment]
目前已经进入出版社审稿的阶段了，估计明年年初就能面市。

**Comment by A-Gan** [comment]
> 目前已经进入出版社审稿的阶段了，估计明年年初就能面市。

这样 还有半年左右，有点久，有办法提前购买到样书之类的吗

**Comment by luopeiyu** [comment]
似乎没有呢，要经过各种审核后才会放出来。有新消息我就会在这里发出来的~

**Comment by zengzizhao** [comment]
现在有出版消息了吗？
主要关心skynet下多 actor 协作的事务问题，因为消息发送机制多个 actor 需要协作时，能否有事务来保证一系列操作的过程中，状态不会被破坏，需要失败后的回退机制，这在网游手游的游戏逻辑中太普遍了，请问书中有涉及这块吗？

**Comment by luopeiyu** [comment]
> 现在有出版消息了吗？
> 主要关心skynet下多 actor 协作的事务问题，因为消息发送机制多个 actor 需要协作时，能否有事务来保证一系列操作的过程中，状态不会被破坏，需要失败后的回退机制，这在网游手游的游戏逻辑中太普遍了，请问书中有涉及这块吗？

hihi，目前进度是在编辑审稿阶段，总体进度比我预计的要慢一些。其实书稿都写完了，就不知道出版社多久能弄好。

**Comment by A-Gan** [comment]
等的花都快谢了[狗头]

**Comment by luopeiyu** [comment]
> 等的花都快谢了[狗头]

排版完成，到总审阶段啦

**Comment by luopeiyu** [comment]
这几天网店陆续上架了^_^  谢谢大家的等待

**Comment by A-Gan** [comment]
> 这几天网店陆续上架了^_^ 谢谢大家的等待

今天上来看到了好消息 买买买  可惜没有第一时间看到
