### ISSUE TITLE
罗老师能教教我一下lua的语法吗？

### ISSUE THREAD

**Issue by dxgzg** [luopeiyu/million_game_server#13]
P21的lua代码没有看懂，没了解过lua，查阅很多资料也没有介绍这种写法，local Role = function，按照我的理解这是定义了一个函数，函数里又包着M这个类对象和M这个类的成员函数，请问是这么理解的吗？原文中记住ROLE是个类，我不太理解，我始终觉得他是个函数。

**Comment by luopeiyu** [comment]
因为Lua中有 8 个基本数据类型，分别为：nil、boolean、number、string、userdata、function、thread 和 table。在这里function也是一种数据类型，它是“第一类值”，可以把它和其他类型等他使用。可以理解成函数里又包着M这个类对象和M这个类的成员函数。

如果要更好的理解，可以关注这两个部分内容：
Lua函数 第一类值
Lua 上值（upvalue）

**Comment by dxgzg** [comment]
感谢
