### ISSUE TITLE
我超期待这本书哎，啥时候出版啊

### ISSUE THREAD

**Issue by jidibinlin** [luopeiyu/million_game_server#3]

**Comment by luopeiyu** [comment]
期待+1，目前到了排版阶段，排版后再还要再做校对，审核~~~
一直在等待，就是很慢啊

**Comment by luopeiyu** [comment]
最新消息，已经进入印刷阶段啦

**Comment by jidibinlin** [comment]
看来得存钱，准备剁手拜读了

**Comment by kkeison** [comment]
那个渠道可以预定或者购买

**Comment by luopeiyu** [comment]
> 那个渠道可以预定或者购买

京东、当当这些电商都会有，应该快了~

**Comment by zengzizhao** [comment]
目前还搜不到，不是说30号上架吗

**Comment by jidibinlin** [comment]
@zengzizhao 已经上架了啊 淘宝就可以搜到，搜百万游戏服务器

**Comment by jidibinlin** [comment]
等不到电子书了，直接入纸质版吧，正好讲了我要学的skynet。毕业设计准备用skynet来的，这就出了教程，狂喜哈哈哈哈。

**Comment by luopeiyu** [comment]
这几天网店陆续上架了^_^  谢谢大家等等
