### ISSUE TITLE
内容还是不够深入

### ISSUE THREAD

**Issue by Gowa2017** [luopeiyu/million_game_server#6]
就我看而言这本书就是对于用sk为例讲解一些例子。

对于sk底层的工作机制也是浅尝辄止。

对于如何驾驭 sk 还是感觉啥了点什么东西。

我很想看到 如何在 sk 上 对服务进行抽象，对常规的世界  角色 场景 战斗 数据共享这方面的知识。

**Comment by luopeiyu** [comment]
定位还是偏入门的书籍；skynet底层工作机制还是有些说明的，第二部分“入木三分”会有些说明，主要是通过用cpp复刻skynet来理解原理。
