### ISSUE TITLE
书籍 21 页底部代码对齐问题

### ISSUE THREAD

**Issue by Jamlee** [luopeiyu/million_game_server#9]
![441634363465_ pic](https://user-images.githubusercontent.com/5196641/137575530-4e0103ff-88c7-4693-bf09-c8c84cd990ef.jpg)
@luopeiyu

**Comment by luopeiyu** [comment]
你好，此处没有问题呢。这段代码中 **表M** 和 **函数M:dispatch** 都包含在 **Role这个函数** 里，所以 **表M** 和 **函数M:dispatch** 是同一陈，而  **Role函数** 更高一层。

**Comment by Jamlee** [comment]
好勒 学习到了
